#!/usr/bin/env python3
from pwn import *
import sys
import subprocess
import os
from fuzz_json import *
from file_type import checkJSON
import concurrent.futures
import multiprocessing
import time

if __name__ == "__main__":
    print("Fuzzing this thing...")
    sampleInput = open(sys.argv[2], 'r')

    binary = sys.argv[1]
    lock = multiprocessing.Lock()
    futures = []

    if bitFlip(sampleInput, binary) == False:
        print("No bad input\n", end="")


        
        
    

            