import imp
from mutators.mutator_base import MutatorBase
from mutators.csv_mutation_fuzzer import CsvMutator
from mutators.json_mutation_fuzzer import jsonMutationFuzzer
from mutators.jpg_mutator import JpegMutator